"""added table for early users

Revision ID: 2e3d17569ad6
Revises: 196632574d29
Create Date: 2025-06-18 06:52:48.523581

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "2e3d17569ad6"
down_revision: Union[str, None] = "196632574d29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "earlyuser",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_earlyuser_id"), "earlyuser", ["id"], unique=False)
    op.create_index(
        op.f("ix_earlyuser_username"), "earlyuser", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_earlyuser_username"), table_name="earlyuser")
    op.drop_index(op.f("ix_earlyuser_id"), table_name="earlyuser")
    op.drop_table("earlyuser")
    # ### end Alembic commands ###
