"""added table for early users

Revision ID: 50cc0f050f59
Revises: 2e3d17569ad6
Create Date: 2025-06-18 07:32:06.789833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50cc0f050f59'
down_revision: Union[str, None] = '2e3d17569ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('earlyuser_email_key'), 'earlyuser', type_='unique')
    op.drop_index(op.f('ix_earlyuser_id'), table_name='earlyuser')
    op.drop_index(op.f('ix_earlyuser_username'), table_name='earlyuser')
    op.create_index(op.f('ix_earlyuser_username'), 'earlyuser', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earlyuser_username'), table_name='earlyuser')
    op.create_index(op.f('ix_earlyuser_username'), 'earlyuser', ['username'], unique=True)
    op.create_index(op.f('ix_earlyuser_id'), 'earlyuser', ['id'], unique=False)
    op.create_unique_constraint(op.f('earlyuser_email_key'), 'earlyuser', ['email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
