"""updated user table

Revision ID: 87420cda0669
Revises: ad36d778f0e3
Create Date: 2025-05-30 08:40:50.928377

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "87420cda0669"
down_revision: Union[str, None] = "ad36d778f0e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email_verified", sa.Boolean(), nullable=False))
    op.add_column(
        "user",
        sa.Column(
            "password_hashed", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "user",
        sa.Column("profile_pic_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("user", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=False))
    op.drop_column("user", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("user", "profile_pic_url")
    op.drop_column("user", "full_name")
    op.drop_column("user", "password_hashed")
    op.drop_column("user", "email_verified")
    # ### end Alembic commands ###
